FROM node:20-alpine AS build

WORKDIR /app
COPY packages/dashboard/package.json ./
COPY package-lock.json ./
RUN npm install
COPY packages/dashboard/ .
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY packages/dashboard/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
